# Generated by Django 3.2.7 on 2021-09-15 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pogscience.storage
import streamers.models


class Migration(migrations.Migration):

    dependencies = [
        ('streamers', '0007_add_twitch_and_gcal_ids_to_scheduled_streams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledstream',
            name='category',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='catégorie du stream'),
        ),
        migrations.AlterField(
            model_name='scheduledstream',
            name='end',
            field=models.DateTimeField(verbose_name='heure de fin prévue'),
        ),
        migrations.AlterField(
            model_name='scheduledstream',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, editable=False, max_length=128, null=True, verbose_name="identifiant interne de l'événement Google Calendar"),
        ),
        migrations.AlterField(
            model_name='scheduledstream',
            name='start',
            field=models.DateTimeField(verbose_name='heure de début prévue'),
        ),
        migrations.AlterField(
            model_name='scheduledstream',
            name='streamer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='streamers.streamer', verbose_name='streamer ayant programmé le stream'),
        ),
        migrations.AlterField(
            model_name='scheduledstream',
            name='title',
            field=models.CharField(max_length=140, verbose_name='titre du stream programmé'),
        ),
        migrations.AlterField(
            model_name='scheduledstream',
            name='twitch_segment_id',
            field=models.CharField(blank=True, editable=False, max_length=128, null=True, verbose_name='identifiant interne du segment Twitch'),
        ),
        migrations.AlterField(
            model_name='scheduledstream',
            name='weekly',
            field=models.BooleanField(verbose_name='hebdomadaire ?'),
        ),
        migrations.AlterField(
            model_name='streamer',
            name='background_image',
            field=models.ImageField(blank=True, null=True, storage=pogscience.storage.OverwriteStorage(), upload_to=streamers.models.background_image_upload_to, verbose_name='image de fond'),
        ),
        migrations.AlterField(
            model_name='streamer',
            name='description',
            field=models.CharField(blank=True, help_text="Une courte description affichée par exemple sur la page d'accueil", max_length=512, verbose_name='courte description'),
        ),
        migrations.AlterField(
            model_name='streamer',
            name='live',
            field=models.BooleanField(default=False, help_text='Est-iel en live actuellement ? Mis à jour automatiquement', verbose_name='en live actuellement ?'),
        ),
        migrations.AlterField(
            model_name='streamer',
            name='live_game_name',
            field=models.CharField(blank=True, default=None, help_text='La catégorie du live en cours, récupéré automatiquement depuis Twitch', max_length=140, null=True, verbose_name='catégorie du stream'),
        ),
        migrations.AlterField(
            model_name='streamer',
            name='live_title',
            field=models.CharField(blank=True, default=None, help_text='Le titre du live en cours, récupéré automatiquement depuis Twitch', max_length=140, null=True, verbose_name='titre du live'),
        ),
        migrations.AlterField(
            model_name='streamer',
            name='long_description',
            field=models.TextField(blank=True, help_text='Description potentiellement très longue affichée sur la page du streamer ou de la streameuse', verbose_name='longue description'),
        ),
        migrations.AlterField(
            model_name='streamer',
            name='name',
            field=models.CharField(help_text="Le nom d'affichage du/de la streamer⋅euse", max_length=128, verbose_name='nom du streamer'),
        ),
        migrations.AlterField(
            model_name='streamer',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=pogscience.storage.OverwriteStorage(), upload_to=streamers.models.profile_image_upload_to, verbose_name='image de profil'),
        ),
        migrations.AlterField(
            model_name='streamer',
            name='twitch_login',
            field=models.CharField(help_text='Utilisé pour récupérer les informations automatiquement', max_length=64, verbose_name="nom d'utilisateur Twitch"),
        ),
        migrations.AlterField(
            model_name='streamer',
            name='user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='compte interne du streamer'),
        ),
    ]
