# Generated by Django 3.2.7 on 2021-09-15 11:43

from django.db import migrations, models
import pogscience.storage
import streamers.models


class Migration(migrations.Migration):

    dependencies = [
        ("streamers", "0008_rename_streamer_verbose_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="streamer",
            name="live_preview",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=pogscience.storage.OverwriteStorage(),
                upload_to=streamers.models.live_preview_image_upload_to,
                verbose_name="aperçu du live",
            ),
        ),
    ]
