# Generated by Django 3.2.7 on 2021-09-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streamers", "0009_add_stream_preview"),
    ]

    operations = [
        migrations.AddField(
            model_name="streamer",
            name="eventsub_subscription_active",
            field=models.BooleanField(default=False, verbose_name="souscription eventsub active ?"),
        ),
    ]
