# Generated by Django 3.2.7 on 2021-09-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streamers", "0012_store_eventsub_secret"),
    ]

    operations = [
        migrations.AddField(
            model_name="streamer",
            name="live_spectators",
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name="spectateurs"),
        ),
    ]
