# Generated by Django 3.2.7 on 2021-09-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streamers", "0013_add_streams_spectators_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="streamer",
            name="colours",
            field=models.CharField(
                blank=True,
                help_text="Liste de trois couleurs principales à utiliser pour habiller ce/cette streamer/euse. Les valeurs sont stockées sous la forme d'une liste de nombres flottants, dont chaque triplet forme une couleur RGB.",
                max_length=62,
                null=True,
                verbose_name="couleurs",
            ),
        ),
        migrations.AlterField(
            model_name="streamer",
            name="live",
            field=models.BooleanField(
                default=False,
                help_text="Est-iel en live actuellement ? Mis à jour automatiquement",
                verbose_name="en live ?",
            ),
        ),
    ]
