# Generated by Django 3.2.7 on 2021-09-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streamers", "0014_add_streamer_colours"),
    ]

    operations = [
        migrations.RenameField(
            model_name="streamer",
            old_name="colours",
            new_name="_colours",
        ),
        migrations.AlterField(
            model_name="streamer",
            name="_colours",
            field=models.CharField(
                blank=True,
                db_column="colours",
                help_text="Liste de trois couleurs principales à utiliser pour habiller ce/cette streamer/euse. Les valeurs sont stockées sous la forme d'une liste de nombres flottants, dont chaque triplet forme une couleur RGB.",
                max_length=62,
                null=True,
                verbose_name="couleurs",
            ),
        ),
    ]
