# Generated by Django 3.2.7 on 2021-10-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streamers", "0016_update_colours_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledstream",
            name="done",
            field=models.BooleanField(default=False, verbose_name="terminé ?"),
        ),
        migrations.AddField(
            model_name="streamer",
            name="live_started_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="L'heure de début du live en cours",
                null=True,
                verbose_name="début du stream",
            ),
        ),
    ]
